kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - dotnet sonarscanner begin 
          /k:"easv-devops_ConsoleCalculatorTLL_AY2xZwalEVvRW2O60D99" 
          /d:sonar.host.url="http://sonar.setgo.dk:9000"  
          /d:sonar.token="sqp_177ae791c19fb8e02b1ec1fd1016badd92be4d1e"
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="sqp_177ae791c19fb8e02b1ec1fd1016badd92be4d1e"